export const products = [
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
    {
        name: "Products name could be here",
        description: 'lorem25',
        liked: false,
        imageURL: "/i.webp",
    },
]